### ISSUE TITLE
Add a loading animation when enter

### ISSUE THREAD

**Issue by JackSuuu** [JackSuuu/jacksuuu-portfolio#4]
# Main idea:

- When the page starts loading, only the spinner is shown.
- Once all resources are loaded, the spinner disappears and your content appears.

# Code example might be useful

HTML

```HTML
<!-- Loading Spinner -->
<div id="loader"></div>

<!-- Main content (hidden initially) -->
<div id="content" style="display: none;">
  <h1>Welcome to my website!</h1>
</div>
```

```CSS
/* Fullscreen Loader */
#loader {
  position: fixed;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  background: white;
  z-index: 9999;
  display: flex;
  justify-content: center;
  align-items: center;
}

/* Simple spinner */
#loader::after {
  content: "";
  width: 40px;
  height: 40px;
  border: 5px solid #3498db;
  border-top: 5px solid transparent;
  border-radius: 50%;
  animation: spin 1s linear infinite;
}

/* Spinner animation */
@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}
```

```
<script>
  window.addEventListener('load', function () {
    document.getElementById('loader').style.display = 'none';
    document.getElementById('content').style.display = 'block';
  });
</script>
```
